# Generated by Django 5.0 on 2024-06-15 12:06

import django.core.files.storage
import django.db.models.deletion
from django.db import migrations, models
from django.conf import settings


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Example",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "input_file",
                    models.FileField(
                        max_length=255,
                        storage=django.core.files.storage.FileSystemStorage(
                            location=settings.MEDIA_ROOT
                        ),
                        upload_to="example",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Example2",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="ExampleFile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "input_file",
                    models.FileField(
                        max_length=255,
                        storage=django.core.files.storage.FileSystemStorage(
                            location=settings.MEDIA_ROOT
                        ),
                        upload_to="example",
                    ),
                ),
                (
                    "example",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="django_file_form_example.example2",
                    ),
                ),
            ],
            options={
                "ordering": ["input_file"],
            },
        ),
    ]
