# Generated by Django 5.1.6 on 2025-02-28 08:15

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_file_form_example", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="example",
            name="input_file",
            field=models.FileField(
                blank=True,
                max_length=255,
                null=True,
                storage=django.core.files.storage.FileSystemStorage(
                    location="/Users/henkjansen/django-file-form/testproject/media"
                ),
                upload_to="example",
            ),
        ),
    ]
