# Generated by Django 3.2.5 on 2021-07-06 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_file_form_example', '0002_auto_20200407_0814'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examplefile',
            options={'ordering': ['input_file']},
        ),
    ]
