# Generated by Django 3.0.5 on 2020-05-01 14:08

import django.core.files.storage
from django.db import migrations, models
import django_file_form.models


class Migration(migrations.Migration):

    dependencies = [
        ('django_file_form', '0005_auto_20200407_0814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='uploaded_file',
            field=models.FileField(max_length=255, storage=django.core.files.storage.FileSystemStorage(), upload_to=django_file_form.models.get_upload_to),
        ),
    ]
